### ISSUE TITLE
Update compsets and tests to use clm6_0, once CAM moves to ctsm5.2.0 or later tag

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CAM#1022]
### What is the feature/what would you like to discuss?

Compsets and tests currently using CLM51 should be updated to CLM60 once CAM uses ctsm5.2.0 or later versions of CTSM. ctsm5.2.0 includes new datasets and hence will change answers from previous ctsm5.1 tags. The CTSM issue about removal of CLM51 is here:

https://github.com/ESCOMP/CTSM/issues/2379

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Any CAM SE can do this

**Comment by cacraigucar** [comment]
@ekluzek - Is this a requirement when we move to ctsm5.2.0, or can it be done in phases?  I'm asking because I was planning on making a quick CAM tag which matches beta17.  I was planning on just updating the externals, but this will bring in ctsm5.2.0.  Do I need to make a change to all of our tests with that tag as well?  The reason I'm making this CAM tag is in preparation for Jim bringing in git-fleximod and having CAM be none-answer changing with his mods.

**Comment by cacraigucar** [comment]
I should also mention that we do not have any tests which are using CLM52, they are all using either CLM50 or CLM51 depending on what we are testing.

**Comment by ekluzek** [comment]
@cacraigucar thanks for the discussion. This is NOT a requirement for using ctsm5.2.0 in CAM. I suggest you do this in phases as you propose. Using CLM50 or CLM51 for now is fine. And it's probably best to NOT clutter the git fleximod update with changes like this. Getting it into the beta tag AFTER git fleximod does sound good to me though...

**Comment by cacraigucar** [comment]
Thanks for the confirmation that we can still use CLM50 and CLM51 for testing purposes.  I am not going to put a calendar timeline on when we phase out the old testing, as we are currently concentrating on creating our CESM3 compsets and tests.  Those _WILL_ use CLM60.  We expect this phase to take some time as "the devil is in the details".  After that phase, we will be looking at current older testing and either eliminating or updating tests to use CAM7.  At that time, we will also update tests to use CLM60.  So our timing on when this is done will be event driven instead of calendar driven.

**Comment by brian-eaton** [comment]
This was resolved in the cam6_4_011 tag during the update to cesm3_0_alpha02a submodules.  CLM60 is now used in all compsets using CAM70.
