### ISSUE TITLE
Update modal dust partitioning for wet and dry deposition

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#1060]
### What is the feature/what would you like to discuss?

The current dry and wet deposition code crudely maps the modal aerosol dust in MAM onto the 4 bulk size bins. A code by Mark Flanner is using erf functions to partition the lognormal distribution into the 4 sectional bins, which maps of the modal size distributions more precisely to the size bins required by the land and ocean models. 

### Is there anyone in particular you want to be part of this conversation?

@tilmes 

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes, but I will need some help

**Comment by tilmes** [comment]
We tested the change and atmospheric diagnostics can be found here:
https://acomstaff.acom.ucar.edu/tilmes/amwg/cam7/f.e23_beta02.FLTHIST_ne30.surf_flux_1995_2004_vs_f.e23_beta02.FLTHIST_ne30.001_1995_2004/website/index.html

@olyson could you check the land diagnostics to make sure this is OK?
@adamrher do you want to confirm that this is OK for the atmosphere?

We probably also want to check the ocean, not sure whom to contact?
Thanks Simone

**Comment by adamrher** [comment]
Thanks @tilmes. I am only seeing marginal increases in dust (near Africa, Australia) with negligible impacts on the TOA radiative budget. Is the marginal increase in dust consistent with your understanding of what this mod does, or is it likely just interannual variability?

**Comment by tilmes** [comment]
This  should be a result of changes in the land, since the atmosphere should not be directly impacted, so hopefully, @olyson can answer this,
Simone

**Comment by olyson** [comment]
Sorry, I don't know anything about this modification so I'm not sure what the expectation is for effects on the land.  As far as I can tell from the case directories, nothing has changed in the land in terms of namelist items or SourceMods and the tags used for these two simulations.  From the description it sounds like the dust, OC, and BC deposition (dry+wet) from the atmosphere will change?  I will run the land diagnostics on these two simulations.

**Comment by olyson** [comment]
The land diagnostics are here:

https://webext.cgd.ucar.edu/FLTHIST/f.e23_beta02.FLTHIST_ne30.surf_flux/lnd/f.e23_beta02.FLTHIST_ne30.surf_flux_1995_2004-f.e23_beta02.FLTHIST_ne30.001_1995_2004/setsIndex.html

I don't see that the global average total dust, BC, and OC deposition are that different:

https://webext.cgd.ucar.edu/FLTHIST/f.e23_beta02.FLTHIST_ne30.surf_flux/lnd/f.e23_beta02.FLTHIST_ne30.surf_flux_1995_2004-f.e23_beta02.FLTHIST_ne30.001_1995_2004/set1/set1_DSTDEP.gif
https://webext.cgd.ucar.edu/FLTHIST/f.e23_beta02.FLTHIST_ne30.surf_flux/lnd/f.e23_beta02.FLTHIST_ne30.surf_flux_1995_2004-f.e23_beta02.FLTHIST_ne30.001_1995_2004/set1/set1_BCDEP.gif
https://webext.cgd.ucar.edu/FLTHIST/f.e23_beta02.FLTHIST_ne30.surf_flux/lnd/f.e23_beta02.FLTHIST_ne30.surf_flux_1995_2004-f.e23_beta02.FLTHIST_ne30.001_1995_2004/set1/set1_OCDEP.gif

The annual mean spatial patterns are similar:

https://webext.cgd.ucar.edu/FLTHIST/f.e23_beta02.FLTHIST_ne30.surf_flux/lnd/f.e23_beta02.FLTHIST_ne30.surf_flux_1995_2004-f.e23_beta02.FLTHIST_ne30.001_1995_2004/set2/set2_ANN_DSTDEP.gif
https://webext.cgd.ucar.edu/FLTHIST/f.e23_beta02.FLTHIST_ne30.surf_flux/lnd/f.e23_beta02.FLTHIST_ne30.surf_flux_1995_2004-f.e23_beta02.FLTHIST_ne30.001_1995_2004/set2/set2_ANN_BCDEP.gif
https://webext.cgd.ucar.edu/FLTHIST/f.e23_beta02.FLTHIST_ne30.surf_flux/lnd/f.e23_beta02.FLTHIST_ne30.surf_flux_1995_2004-f.e23_beta02.FLTHIST_ne30.001_1995_2004/set2/set2_ANN_OCDEP.gif

There are some small differences in albedo but those can probably mostly be attributable to variability:

https://webext.cgd.ucar.edu/FLTHIST/f.e23_beta02.FLTHIST_ne30.surf_flux/lnd/f.e23_beta02.FLTHIST_ne30.surf_flux_1995_2004-f.e23_beta02.FLTHIST_ne30.001_1995_2004/set2/set2_ANN_ASA.gif

I will ping Will Wieder so that he is aware of these changes.

**Comment by tilmes** [comment]
Thanks for the analysis, the total average dust, BC and OC burden going to the land should not change, what has changed is in what bins it is included.

**Comment by olyson** [comment]
When you say it shouldn't change, do you mean it wll be bfb, or roundoff, or larger than roundoff?  I see differences that are small but seem to be larger than roundoff:

https://webext.cgd.ucar.edu/FLTHIST/f.e23_beta02.FLTHIST_ne30.surf_flux/lnd/f.e23_beta02.FLTHIST_ne30.surf_flux_1995_2004-f.e23_beta02.FLTHIST_ne30.001_1995_2004/set1/set1Diff_DSTDEP.gif
https://webext.cgd.ucar.edu/FLTHIST/f.e23_beta02.FLTHIST_ne30.surf_flux/lnd/f.e23_beta02.FLTHIST_ne30.surf_flux_1995_2004-f.e23_beta02.FLTHIST_ne30.001_1995_2004/set1/set1Diff_BCDEP.gif
https://webext.cgd.ucar.edu/FLTHIST/f.e23_beta02.FLTHIST_ne30.surf_flux/lnd/f.e23_beta02.FLTHIST_ne30.surf_flux_1995_2004-f.e23_beta02.FLTHIST_ne30.001_1995_2004/set1/set1Diff_OCDEP.gif

**Comment by olyson** [comment]
Differences in H2OSNO at high latitudes.  I do see increases in H2OSNO, particularly around Greenland and the Canadian Arctic.  But the changes are fairly small compared to the overall snowpack there, so maybe it's just variability, particularly since I don't see big changes in dust, BC, and OC there.

![surf_flux-control ANN H2OSNO diff polar](https://github.com/user-attachments/assets/fbed7a21-699d-47a8-a9cf-208c04a6dfcb)

**Comment by cenlinhe** [comment]
The difference in land surface variables and aerosol deposition fluxes look reasonable to me. It seems that the change in dust depo flux is mainly through the feedback to precipitation.

**Comment by tilmes** [comment]
@fvitt We need to check with Keith Lindsey to see if he is okay with the pull request. I don't know his GitHub account.

**Comment by fvitt** [comment]
@klindsay28 Can you weigh in on this issue?

**Comment by klindsay28** [comment]
I think this is fine with ocean BGC. We might need to retune ocean BGC, but that is already to be expected with other changes in the coupled model.
