### ISSUE TITLE
Implement Climate-Chemistry compset

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#1064]
### What is the feature/what would you like to discuss?

Implement a compset for chemistry-climate simulations.

See test case below, provided by @tilmes, which includes a simpler chemistry mechanism and appropriate namelist settings:

```
/glade/campaign/cesm/cesmdata/cseg/runs/cesm2_0/f.cam6_3_160.FCMT_climate_chemistry_ne30.moving_mtn.001
```

### Is there anyone in particular you want to be part of this conversation?

@lkemmons 

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes

**Comment by tilmes** [comment]
@fvitt @lkemmons I think, the co-chairs discussion was suggesting this:

CTS1: “full” troposphere-stratosphere chemistry), CTS2, CTS3
CSC:  simplified chemistry for climate (~40% cheaper)		
CSO: Specified oxidants chemistry (used in BLT and BMT)	

so, I guess, we for now keep the FCMT compset for the full chemistry, and would call it FCSCMT (although in the past, SC was used for specified chemistry). 
I am adding @PeterHjortLauritzen and @cecilehannay since I am not sure if we had agreed on something already.

Thanks Simone

**Comment by PeterHjortLauritzen** [comment]
Please ask Dave Lawrence (not sure compset names have been completely settled yet)

**Comment by tilmes** [comment]
@fvitt for now, I guess, we could call it FCts4MT and change it when there is a decision?
For we call it FCSCMT..
