### ISSUE TITLE
Output grid definitions

### ISSUE THREAD

**Issue by AndrewJConley** [ESCOMP/CAM#280]
All dynamical cores need to output grid structure.  
At the moment the grid centers are available but for SE, the grid boundaries are not specified.

It is unclear what the grid boundaries should be for the quadrature points inside each element, but many of the postprocessing tools need to know the grid definition.  Just to throw an idea out there, perhaps we could compute grid boundaries based on the quadrature weights, even if that is not a precise definition of the grid?

**Comment by adamrher** [comment]
There is already a definition of the control volumes around gll nodes, as this is req'd by the coupler. They are constructed in a similar way as you suggest, polygons around nodal points whose area is iterated to match the quadrature weight * metric term. These control volumes are available from the SCRIP file.

I think these vertices should be available in the history i/o as well.

**Comment by AndrewJConley** [comment]
The energies must be embedded in the code of the *hrates subroutines in mo_jshort and mo_jlong.  
See:
https://github.com/ESCOMP/CAM/blob/cam_development/src/chemistry/mozart/mo_jshort.F90
https://github.com/ESCOMP/CAM/blob/cam_development/src/chemistry/mozart/mo_jlong.F90

**Comment by andrewgettelman** [comment]
As I understand it, we need to implement the UGRID conventions in our netCDF files for many tools to read the grids correctly:

http://ugrid-conventions.github.io/ugrid-conventions/

**Comment by andrewgettelman** [comment]
From @patcal:  (Patrick Callaghan)

  I talked with the CSEG group about the history file issue yesterday. 
As I mentioned to them: I checked that values needed for Paraview 
are { ncells, element_corners(4,ncells) } and I can adapt to those, but 
I need to check if those are standard for a UGRID. Also, when I worked 
on this >4 years ago, I had modified a version of the source to write out
the values I needed, so I need to try and find that so when I opened the
issue I could recommend the needed changes.

**Comment by andrewgettelman** [comment]
From @adamrher  
Also, Do you mean that paraview needs the vertices of the SE control volumes, not the element vertices, right? In which case the number of vertices is up to 12 for var-res, if I'm not mistaken.

**Comment by patcal** [comment]
Follow up:
The only additional information needed on the SE history files is an array
of indices identifying the bounding points for each quadrilateral area in 
the SE grid. (the region enclosed by each 4 neighbouring SE grid points)
This information is already available in CESM, it is returned by the 
CreateMetaData() routine in dof_mod.F90  
In the past, this information was written to a separate file in the <run> directory 
for each case at model start-up. This practice was stopped at some point, as 
that file no longer shows up in <run>. When I developed the reader plugin for 
VisIt, I followed the format from that netcdf file: 

   int    ncorners = 4
   int    ncenters =   nnnnn  (number of quadrilateral regions in the SE grid)
   int    element_corners(ncorners,ncenters)

In ParaView, the reader plugin looks for the same integer array:

    int element_corners(4,ncells)

but the "4" is hard coded and instead of using ncenters, the other dimension is 
defined as ncells. 

I have heard but not seen that there are other display programs that can display 
unstructured (SE) grids, but they adhere to the UGRID standard/convention for 
how those grids are stored. Using a standard always seems like a good idea, but 
in this case it would require that the existing lat(ncol), lon(ncol) arrays that many 
post-processing codes look for and rely on would also need to be changed.  
I see this option as a no-go at this point. 

I can adapt the VisIt reader to use any renamed variation of the variables, so the 
easiest path forward would be to add 'element_corners' to the history files using the 
dimension 'ncells'. The 'ncorners' dimension can be renamed to be anything, if 
there is a more descriptive/appropriate name, since ParaView ignores it. This 
change will allow for ParaView/VisIt to seamlessly open and use SE gridded data 
files. 

Also, I mentioned in an off-line meeting that I had a modified version of the model 
that already added this info to the default output for SE history files. I have not been 
able to track those mods down, so they appear to have been lost either in the glade 
migration or as a result of the catastrophic disk failure (CGD) that happened a couple 
of years ago.

**Comment by andrewgettelman** [comment]
I don't see why we cannot adhere to the UGRID standard and still have a variable for lat and lon. It's not clear to me whether the mesh description needs to be in each file, or if we should just write one file at startup (as it seems SE used to do). We might need to survey analysis workflow: what software will we use (likely python) and what is the best way to work with unstructured grids?  We can then propose a framework that will work for our different unstructured (non lat-lon) grids (SE, MPAS, probably FV3 as well). 

I think we should get used to output that is in column format, and do our lat-lon converting at analysis, NOT converting and storing lat-lon gridded output history files from the model. 

Thoughts? Do we entrain other SE and MPAS experts in this discussion?

**Comment by brian-eaton** [comment]
The UGRID convention is a spin-off from CF.  It doesn't contain anything that conflicts with the CF conventions which our history files conform to.  In particular, there are no conventions for the names of variables or dimensions in the file.  The conventions are for the names of attributes which describe specific features of a mesh, and the attributes then point to the variables in the file.

**Comment by andrewgettelman** [comment]
Thanks for pointing that out Brian. So it seems like we just need to add attributes to our coordinates, and add the variable that @patcal noted with the right attributes. This seems like it will make it easy to adapt what we have now to conform to the UGRID standard. 

It would be useful to get scientific input (and maybe a working group) on the analysis tools and workflows that people anticipate (we would need to include the MPAS group).

**Comment by adamrher** [comment]
> The only additional information needed on the SE history files is an array
of indices identifying the bounding points for each quadrilateral area in
the SE grid. (the region enclosed by each 4 neighbouring SE grid points)
This information is already available in CESM, it is returned by the
CreateMetaData() routine in dof_mod.F90

@patcal can these vertices also be used to regrid using the ESMF tools? Does the global sum of the areas equal a sphere? I usually use the vertices from the SCRIP file for remapping SE grids (which are different from the vertices you are referring to), but it would be convenient if all the information req'd to generate remapping wgts were contained in the history files.

**Comment by andrewgettelman** [comment]
@patcal and I discussed Grid names today. It seems like we could match a name string in a file with the number of points and those 2 pieces of information could verify a grid is the same as another. We also discussed a naming convention for grids, that might look like this:

Grid name = <dycore>_<horiz>_<vert>

Where: <dycore>:  mpas, fv3, fv, se, secslam
	<horiz> : determined by dy core. But if the grid is a refined mesh it needs an identifying name (see below)
	<vert>:  includes the type of levels, the number and an L at the end.... Where type is:
			sigma-pressure: sp, Height: h, Pressure: p

Examples: fv_19_sp23L, se_ne30np4_sp58L, se_ne0np4.conus.ne30x8_sp32L

Thoughts?

**Comment by AndrewJConley** [comment]
I would think you'd want a separate specification of the vertical grid and
the horizontal grid.

I would also think you would want to support a generic unstructured grid,
of which FV would be a special case.

I also expect that if the generic unstructured gid is not possible, you'd
want a "grid type" key.  Annotations describing could be added, but the
underlying grid would be defined by the vertices, without need to reference
the annotation.

Perhaps for SE or MPAS the native information about the grid structure
could be included as well.

**Comment by gold2718** [comment]
I believe this issue has been supersedes #468 so I am closing this one (but this message will add a link to the new issue).
