### ISSUE TITLE
outfrq9s_multi multi modifier not required 

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#358]
Note that test SMS_Ln9_Vnuopc.f19_f19_mg17.FXHIST.cheyenne_intel.cam-outfrq9s_multi
is equivalent to SMS_C3_Ln9_Vnuopc.f19_f19_mg17.FXHIST.cheyenne_intel.cam-outfrq9s

There is no need for this testmods_dir

https://github.com/ESCOMP/CAM/tree/cam_development/cime_config/testdefs/testmods_dirs/cam/outfrq9s_multi

**Comment by cacraigucar** [comment]
@jedwards4b - I am putting together a misc CAM tag and was possibly including this.  But, I see in the shell_commands that the outfrq9s_multi has `./xmlchange NINST=2`.  That along with giving information for additional output files in the user_nl_cam shows that these are subtly different.  

It appears that the SMS_C3 is doing the multi-instance.  I did a quick google search and it looks like from a github comment, that SMS_C3 is doing an NINST=3.  But, I was unsuccessful in finding any official documentation on this.  @jedwards4b - can you point me to the documentation?

I am tempted to keep this test as it is, since it is not an error.

@fvitt - since this is your test, do you have an opinion?

**Comment by jedwards4b** [comment]
So the issue is 2 instances vs 3?  Change the test to SMS_C2 then.  Documentation is [here: ](http://esmci.github.io/cime/versions/master/html/users_guide/testing.html) in the modifiers section.

**Comment by fvitt** [comment]
The outfrq9s_multi is my creation.  It is fine to do away with it.  Do as @jedwards4b suggests and use SMS_C2 (for 2 instances).  I had no clue the _C testing option was available.  Is there a good place to find the available testing options?

**Comment by jedwards4b** [comment]
[here](http://esmci.github.io/cime/versions/master/html/users_guide/testing.html)

**Comment by cacraigucar** [comment]
I too didn't know about the _C# option and wasn't successful in finding the documentation.  Thanks @jedwards4b for the link to it.  I will include this in my upcoming misc CAM tag.
