### ISSUE TITLE
ERP_D_Ln9.f09_f09_mg17.FSD.cheyenne_intel.cam-outfrq9s_contrail  does not run for cesm2_3_alpha02d

### ISSUE THREAD

**Issue by fischer-ncar** [ESCOMP/CAM#362]
ERP_D_Ln9.f09_f09_mg17.FSD.cheyenne_intel.cam-outfrq9s_contrail is failing with the following error.

99:MPT ERROR: Rank 99(g:99) received signal SIGFPE(8).
99:     Process ID: 35145, Host: r9i7n8, Program: /glade/scratch/fischer/t/cesm2_3_alpha02d_alpha_intel/ERP_D_Ln9.f09_f09_mg17.FSD.cheyenne_intel.cam-outfrq9s_contrail.GC.c2_3_a2d_int/bld/cesm.exe
99:     MPT Version: HPE MPT 2.21  11/28/19 04:21:40
99:
99:MPT: --------stack traceback-------
99:OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.

**Comment by cacraigucar** [comment]
@fvitt - What are your thoughts on the following?

This test is running a HIST_CAM60%SDYN instead of the SDYN%CAM60 which was intended.  We will need to introduce a new compset to make a non-historical SD run.

Suggestion from Chris Fischer:
I think the best way to run a SDYN instead of a HIST test is to change the FSD compset and rename the old FSD to FSDHIST.
Something like this.

   <compset>
     <alias>FSDHIST</alias>
     <lname>HIST_CAM60%SDYN_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV</lname>
   </compset>
   <compset>
     <alias>FSD</alias>
     <lname>SDYN_CAM60%SDYN_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV</lname>
   </compset>

**Comment by fvitt** [comment]
@cacraigucar, 
I am not a fan of the short name FSDHIST.  Can you explain what is meant by "SDYN%CAM60"?  Why does the contrail test need to be non-historical?  It might be helpful if you could explain the cause of the test failure

**Comment by cacraigucar** [comment]
@fvitt  I'm not sure what exactly the reason is for the failure (see the error message that Chris posted in the description of this issue).  When I went to compare with the longname that Jack was using for his runs and what I used for testing, I realized that we were not using the historical descriptor.  I then realized that putting jet airplanes in the 1850's was not accurate and didn't spend further time debugging.  It probably is because his input files are for the jet era.  

That said, I believe we need a SDYN compset which is not historical.  Should we go generic and if so, do you have a suggestion or should I go ahead and make it specific for contrails - FCONTRAIL or something like that?  I'll probably get feedback from  @chihchen24 and @andrewgettelman if we go for a specific compset.

**Comment by andrewgettelman** [comment]
The standard way to run with contrails would be SDYN, F2000climo or FHIST in the recent period. For testing simplicity I think I would do the test with F2000climo if FHIST is defaulting to 1850.

Does that help?

**Comment by fvitt** [comment]
Does this regression test need to have specified dynamics?  Will a free running configuration suffice to exercise the contrail emissions capabilities?  In my opinion, the simple fix is to use compset FHIST and set the start date to the beginning of the airplane emissions in the contrail inputs.

**Comment by andrewgettelman** [comment]
Francis' suggestion works for me. Set FHIST and start date of 1-1-2006

**Comment by cacraigucar** [comment]
Alternatively I am testing whether I can use the longname that Jack was using in the regression test.  If that works, I'd probably go with that.  Otherwise I set up the test to use FHIST and start data of 1-1-2006
