### ISSUE TITLE
Missing inputs in aqua-planet compsets

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#413]
Does anyone know why the inputs of emissions and prescribed oxidants are disabled in the cam5 and cam6 aqua-planet use cases?

In  aquaplanet_cam5.xml and aquaplanet_cam6.xml we have:
```
<ext_frc_specifier        > ""    </ext_frc_specifier>
<srf_emis_specifier       > ""    </srf_emis_specifier>
<tracer_cnst_specifier    > ""    </tracer_cnst_specifier>
```

In my opinion, the aqua-planet tests cam5 and cam6 ought to include inputs of the prescribed oxidants and emissions for the chemistry.

**Comment by gold2718** [comment]
This seems to go back quite a ways -- this change was introduced in cam5_4_126 with the description:
> CESM-aquaplanet is now supported out-of-the-box via prescribed-SST (QPCx) and slab-ocean (QSCx) compsets (where x is CAM version).

No explanation for these namelist entries is given. @cacraigucar, @Katetc, you are listed on that tag, any ideas?

**Comment by Katetc** [comment]
Errrrm, I only maybe barely remember helping out on this one. I think Cheryl went on vacation and Cecile was anxious to get these compsets set up. So, I ended up doing a bunch of testing to get the use cases to match Cecile's runs b4b. Which took a whole weekend, but I got it in the end. If there are missing forcing files, that's because Cecile didn't have them in her example case at the time. I also remember a research report from Brian Medarios questioning what emissions should be used in an aquaplanet simulation. Because the places that are the source of many emissions (large cities) aren't on the planet any more. Maybe we should also ask him what he would expect here? I don't know his GitHub name....

**Comment by gold2718** [comment]
@brianpm, any ideas?

**Comment by brianpm** [comment]
This decision was made in order to remove aerosol-cloud interaction (and aerosol-radiation interaction) from the aquaplanet configurations to the extent possible. This follows the experimental protocol for the CFMIP aquaplanets, and is consistent with previous aquaplanet experiments.

**Comment by cacraigucar** [comment]
@fvitt - Did this answer your question?  If so, please close this issue.

**Comment by fvitt** [comment]
Thanks for all the feedback.
