### ISSUE TITLE
Bug in cam_dev setup using FWscHIST

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#488]
@cecilehannay  reported a bug using the new cam_dev setting: 

I am getting an error with the new sandbox. 

Case directory is:
/glade/p/cesmdata/cseg/runs/cesm2_0/f.e21.FWscHIST.ne30_L48_BL10_cam6_3_039.001.hf2

ERROR:
  cnst_chk_dim: FATAL: number of advected tracer (          41 ) not equal to pc
 nst (          43 )

One thing that I forgot to mention is that we have been running FWscHIST and not FHIST.

**Comment by gold2718** [comment]
This seems to be a user error. The reason is that `-phys cam_dev` sets the microphysics to `mg3` but you are overriding this with `micro_mg_version = 2` in user_nl_cam. To get this configuration to work, I suggest using the override in configure:
```
./xmlchange CAM_CONFIG_OPTS=-phys cam_dev -microphys mg2 -age_of_air_trcs -chem waccm_sc_mam4 -cppdefs -Dwaccm_debug -nlev 58
```
There is also an option, `-nadv` that you can add to `CAM_CONFIG_OPTS` to override the total number of tracers but I do not think you will need it if you use the microphysics override.

**Comment by cacraigucar** [comment]
@adamrher did confirm that the reset of mg3 to mg2 in user_nl_cam was the source of the error and that this was not a bug.

Closing issue
