### ISSUE TITLE
Add a smyle L83 compset 

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#511]
For CESM2.1 Branch: 

Add a SMYLE 83 level compset

@adamrher, @ekluzek and @islasimpson may have some input on this.  There was discussion at the Jan 25 9AM AMP SE meeting on this topic and an issue was requested to have this discussion documented

https://github.com/ESCOMP/CAM/pull/510

**Comment by adamrher** [comment]
I was seeking clarification on this L83 grid. Is this just a one off for this SMYLE project? As many are aware, we are developing new workhorse vertical grids L58/L93 slated for CAM7. These require careful tuning as the physics/dynamics are very sensitive to vertical grid resolution, and so I was curious what type of validation has been performed of the L83 grid relative to previously established baselines such as L32/L72. I would imagine this to be important if the L83 grid were to become operational in some sense.

I'm probably late to the party, so perhaps I should mind my own bee's wax.

**Comment by islasimpson** [comment]
This is a one off for this SMYLE project.  It's using the finite volume dycore and no tuning to the physics except for some gravity wave drag tuning.  This configuration is without the additional boundary layer changes doesn't require such extensive tuning as the physics are not so sensitive to changes in the vertical grid when you don't touch the boundary layer.  We did extensive analysis of runs that are similar to this throughout the process of deciding on the next vertical resolution.  We did some additional tuning of this configuration to try to sort out the sudden warming frequency.  Water vapor is still an issue but that's not so important for this project because they are short initialized predictions.  In coupled simulations there were some issues with too much sea ice initially.  After running a 100 year long simulation though that bias was less sever than originally thought, although it remains.  But we consider this to not be too much of an issue for this particular project, again because they are initialized predictions.  Overall, we think this configuration is good enough for this purpose.  We want to avoid doing any additional tuning because the purpose is to explore the sensitivity of seasonal predictions to vertical resolution and avoid other differences to the model.  We need to look at the 100 year long coupled simulation in more detail but I think given the timescale on which Scripps needs to use their computing resources, this is about as much validation as is going to be done at this point.

**Comment by adamrher** [comment]
Thanks Isla. I know ur uber busy so I appreciate the background. I feel more comfortable that the boundary layer resolution is untouched, as that seems to be the leading cause of rogue climates in our experience (w/ o additional tuning or fiddling).
