### ISSUE TITLE
Bring in new CLUBB External

### ISSUE THREAD

**Issue by Katetc** [ESCOMP/CAM#515]
There is a new CLUBB version available and being integrated into CAM currently. During this work, we hope to address some other issues such as:
Issue #467 Add new CLUBB invrs_tau coefs to be set via namelist
Issue #461 DP_FRAC and SH_FRAC not initialized in clubb_intr
Issue #429 clubb stats history fields jumbled for threaded runs

There are other open CLUBB issues on https://github.com/ESCOMP/CAM/ , but are not slated to be addressed here. Please comment on this issue if there are any that I've missed and should be included.

There are currently no open issues on https://github.com/larson-group/clubb_release and the only open issue on https://github.com/ESCOMP/CLUBB_CESM/ is from @megandevlan and won't be addressed here.

**Comment by cacraigucar** [comment]
@Katetc - After today's meeting in an email with @adamrher, he said that in his opinion #429  and #461 are lower priority.  Do you agree that these should be removed from this issue or do you want to continue bringing them in?

**Comment by adamrher** [comment]
@Katetc following up w/ some nuance. It looks like https://github.com/ESCOMP/CAM/issues/461 is as simple as initializing ```dp_frac = 0._r8``` and ```sh_frac = 0._r8``` in ```clubb_intr.F90```. Which seems trivial to include. I guess it's https://github.com/ESCOMP/CAM/issues/429 that I don't consider a high priority ... but having looked over katie's branch, this might be fixed by the new workflow of the stat variables?
