### ISSUE TITLE
Noise in derived quantities in ne30pg3 configuration #551

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [ESCOMP/CAM#551]
Issue: Topography induced noise in spectral-element physics grid configurations (NOT np4 configurations) in derived quantities such as PSL, eddy Z500, etc.

Reason: Derived quantities are sensitive to how variables are mapped to physics grid. In particular, PHIS is read in on physics grid and mapped (using degree 3 tensor interpolation) to GLL grid but not mapped back to physics grid. Consequently T and PHIS are not "consistent" in terms of both being mapped from GLL to physics grid.

Solution: map PHIS from GLL to physics grid in dp_coupling. This is a one line code change in src/dynamics/se/dycore/fvm_mapping.F90, that is, replace line 452

phis_phys(:,ie) = RESHAPE(fvm(ie)%phis_physgrid,SHAPE(phis_phys(:,ie)))

with

phis_phys(:,ie) = RESHAPE(dyn2phys(elem(ie)%state%phis(:,:),elem(ie)%metdet(:,:),inv_area),SHAPE(phis_phys(:,ie)))

**Comment by zarzycki** [comment]
Thanks for opening this. I can confirm that making this one line mod does produce a much smoother PSL climatology (ex below, one-month PSL w/ F compset with ne30pg3 with fix (left) and current trunk (right)).

![PSL_w_fix](https://user-images.githubusercontent.com/10341827/159765556-753108fd-a65a-4c2d-918a-f2e3508a2dc2.png)

It is worth noting that this update would be "answer changing" since PHIS is used by a few pieces of code in the physics. Ex. I see with grep: Line 647 of zm_conv_intr.F90, L3140 in clubb_intr.F90, etc. So I do not get BFB climos in both of the above runs.

So if we *only* want to correct the noise in derived PSL, we should probably pass a "dummy" PHIS field to phys. That said, I can't think of a reason why any code on the physics side should be using PHIS on the GLL nodes, so I would think the above would make the PHIS field consistent w/ other vars being used in the subgrid suite.
