### ISSUE TITLE
SCAM with cam_dev physics not computing fluxes with current UBOT 

### ISSUE THREAD

**Issue by megandevlan** [ESCOMP/CAM#570]
In looking into the simulation of U10 a bit more for #540, a few SCAM tests are showing strange results depending on the choice of physics package. Ultimately, when SCAM is run with CAM6 physics, the values of U10 and the lowest model level wind speeds look fairly normal. But when switching to camdev physics (using cam6_3_045), it looks like there's a few issues in how UBOT is getting passed to  `shr_flux_mod.F90` at each time step (fig below). But the behavior seems to be different across various IOP's (I've tested BOMEX and TOGA so far): 
![Screen Shot 2022-04-12 at 2 24 08 PM](https://user-images.githubusercontent.com/42625059/163047413-4b0add03-0a05-4c47-9511-1af2f118d964.png)

For a bit more context on that figure - I added a bunch of print statements to the flux module to write out the values of vmag, ubot, etc. at each time step here: `/glade/work/mdfowler/gust_cam7/cam_mods/printU10stuff/shr_flux_mod.F90` and ran the two 58L cases (cam6 vs cam_dev physics) with the BOMEX and TOGAII IOPs. In the BOMEX case, it looks like the winds aren't actually getting passed through to the coupler beyond the first time step (i.e., the value of vmag is stuck at 8.75 for the entirety of the run). In the TOGA case, _something_ is getting passed but the values that the flux calculation sees for `ubot` don't line up with what's output in the history file for the lowest model level U values: 
![Screen Shot 2022-04-12 at 2 26 01 PM](https://user-images.githubusercontent.com/42625059/163047703-4116fc6a-6b93-40f5-8b27-2f178b42b288.png)

A test just now with cgilsS6 showed similar behavior to the bomex case - the value of vmag is stuck at 8.13 m/s for every time step and isn't updating. I'm not sure why different IOPs are behaving differently in terms of the winds getting passed to the coupler over ocean grid points.

**Comment by adamrher** [comment]
OK. I think this makes sense. UBOT in the history file always pertains to the state of the winds just after CLUBB/MG2. In CAM6, the winds after CLUBB/MG2 are identical to the winds sent to the CPL; The CAM6 ordering goes:

-  dycore->deepconv->CLUBB/MG2->bc_history_write->radiation->CPL

UBOT in the history files pertains to the state of the winds in bc_history_write. Since radiation doesn't change the winds the CPL see's that same state.

In contrast, CAM_DEV process ordering is:

- dycore->deepconv->CPL->CLUBB/MG2->bc_history_write

So the winds in shr_flux_mod are basically the dycore winds that have (potentially) been adjusted by convective momentum transport in deepconv. The reason the winds are a constant for the BOMEX case is b/c the SCAM dycore step resets the winds to that in the ncdata or iop file (I can't remember which). And so I suspect if you go into those files you'll see the winds are constant at 8.75 m/s. Whereas in CAM6, you're seeing the 8.75 m/s winds *after they have been adjusted by CLUBB*.

So the point is that in CAM_DEV the history fields are not reflective of what's seen by the CPL. I don't think there's anything wrong with that; where we output the fields in the time-loop is already a bit hand-wavy ... whose to say one place is better than the other?

**Comment by megandevlan** [comment]
@adamrher, this makes a lot more sense. You're absolutely right, the winds that are specified in the IOP file are constant for BOMEX and equal to 8.75 the whole time; for the TOGA run too, those IOP winds look to be what's used in the coupler, not the winds after being modified by CLUBB/MG2. So this isn't a bug, just a facet of where the output is relative to the winds used for the U10 calculation. 

Agree, this might not matter in the end for where we output the fields... I'll go ahead and close the issue tomorrow unless anyone has other concerns.
