### ISSUE TITLE
clubb is applying wet, instead of dry mixing ratio tendencies to the physics state array

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#613]
### What happened?

The physics state array is supposed to contain dry mixing ratios. At the top of the clubb subroutine, it converts (a copy of) the state array to moist mixing ratios, since clubb operates on moist mixing ratios. This implies that the resulting ptend array is formulated with wet mixing ratio tendencies. I believe that the tendencies should be converted to dry mixing ratios before doing a physics_update. This is not currently being done.

An analogue is how mixing is done in vertical_diffusion.F90. At the top of the main subroutine it converts mixing ratios to wet. It then converts the resulting tendencies to dry mixing ratio tendencies, by scaling them by dp/dpdry:

```
  ! Convert tendencies of dry constituents to dry basis.
  do m = 1,pcnst
     if (cnst_type(m).eq.'dry') then
        ptend%q(:ncol,:pver,m) = ptend%q(:ncol,:pver,m)*state%pdel(:ncol,:pver)/state%pdeldry(:ncol,:pver)
     endif
  end do
```

I believe a similar conversion should be applied to the clubb tendencies computed in clubb_intr.F90

@quantheory @bogensch wanted to bring you two in just to help confirm whether this is a real issue.

### What are the steps to reproduce the bug?

run the model

### What CAM tag were you using?

any tag

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

Yes

**Comment by quantheory** [comment]
I can't say I have a complete grasp of how `clubb_intr` is put together; I think most of the work of putting CLUBB into CAM was done by Pete and one of the other SEs (Cheryl?).

That said, your comment makes sense, but I think the conversion you suggest is already being done on these lines:

https://github.com/ESCOMP/CAM/blob/cam_development/src/physics/cam/clubb_intr.F90#L3932-L3942

I'm not sure if there is some subtle inconsistency in doing it this way rather than at a different point in the code, but at first glance it seems fine to me.

**Comment by adamrher** [comment]
well, I'm really glad I ping'ed you b/c you're pointing out this is already done. I'm embarrassed I missed this ... I didn't scroll far enough down to see it is scaling the ```ptend_all``` array by dp/dpdry. I'm. always learning new things about clubb_intr...

So this is not an issue. I'll close this tomorrow.

**Comment by adamrher** [comment]
issue is not an issue
