### ISSUE TITLE
convect_shallow.F90 has CIN in an addfld call, but there is no corresponding outfld call

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#674]
### What happened?

A user in the forum reported running with an FHIST compset, and added CIN to his fincl call.  His output was filled with zeroes.  A visual inspection of physics/cam/convect_shallow.F90 finds an addfld call for this variable, but an outfld call does not exist in this routine.  I was also unable to find an outfld call for CIN using grep through the source code tree.

### What are the steps to reproduce the bug?

I did not run a job to verify this

### What CAM tag were you using?

cam6_3_072

### What machine were you running CAM on?

Other (please explain below)

### What compiler were you using?

Other (please specify below)

### Will you be addressing this bug yourself?

No

### Extra info

This is being reported based on a forum user's report and a visual inspection of the code.

**Comment by adamrher** [comment]
I don't know if there at one time was some outfld call in convect_shallow, but it's gone now. I *think* the only CIN calculation is done in uwshcu.F90 ... indeed this is the only module that pops up when you grep CIN. There are special UW CIN outflds that are setup in the ```init_uwshcu```

```
    call addfld( 'cin_Cu'         , horiz_only,    'A', 'J/kg'    , 'CIN upto LFC'                                         )
    call addfld( 'cinlcl_Cu'      , horiz_only,    'A', 'J/kg'    , 'CIN upto LCL'                                         )
```

These variables are not available at the convect_shallow.F90 level and so my take-away is that we should just delete the addfld call to CIN in convect_shallow.F90 since it' doesn't seem to have a purpose. Maybe @swrneale has more information?

**Comment by adamrher** [comment]
This little 'bug' has probably been around a while ... it means less to me now since we don't use convect_shallow.F90 in cam_dev (I made a trimmed down version and named it physics/cam_dev/convect_diagnostics.F90). But I don't see the harm in removing this addfld call from convect_shallow.F90.
