### ISSUE TITLE
New chemistry mechanism for CAM7 prognostic GHGs

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#762]
### What is the feature/what would you like to discuss?

A WACCM-SC like mechanism is needed which will include prognostic CO2

### Is there anyone in particular you want to be part of this conversation?

@dan800 @lkemmons @tilmes

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes, but I will need some help

**Comment by dan800** [comment]
Suggestion for names for the mechanism? Mine would be "GHG-MAM4"

**Comment by swrneale** [comment]
MGC - Minimal GHG Chemistry?

**Comment by tilmes** [comment]
I would call it MAM4 chemistry regarding the aerosols, so GHG-MAM4 seems good to me

**Comment by adamrher** [comment]
In another thread I said:

> @dan800 @fvitt are the lbc's for CO2 latitudinally and seasonally varying, as Dan had suggested?

and Dan responded by inquiring about the lbc file currently used in FHIST. I can confirm that the file he pointed to:
```
/glade/p/cesmdata/cseg/inputdata/atm/waccm/lb/LBC_17500116-20150116_CMIP6_0p5degLat_c180905.nc
```
Is what is used in FHIST. The file contains CO2 LBC's as a function of latitude and time. However, the CO2 values in that file are constant with latitude; only varying with time.

@dan800 are you proposing both to have (a) CO2 LBC's vary by latitude, AND (b) CO2 LBC's to vary by longitude? Does such a file exist, or do we have to create it? I believe the ghg_mam4 PR https://github.com/ESCOMP/CAM/pull/766 as of now does not change the LBC file. So I don't think this is on the radar for that PR. Should it be?

**Comment by dan800** [comment]
@adamrher I am surprised that it constant with latitude, but hey, maybe that's the design of CMIP6. A good question for Doug.  Still, the only thing I am proposing is that 'CO2' be added to the flbc_list if Francis has not already done it. Otherwise, I fear the model will break. The issue of what will actually go into CMIP7 forcing files is different.

**Comment by fvitt** [comment]
@adamrher and @dan800  I took a look at `CO2_LBC` in file `LBC_17500116-20150116_CMIP6_0p5degLat_c180905.nc`.  It varies with latitude and time.

**Comment by dan800** [comment]
@adamrher This is what I meant by the Keeling wiggles. This if from the current LBC file and you can see the seasonal variations in CO2 are not the same between hemispheres.
![keeling](https://user-images.githubusercontent.com/37961632/226052248-c31321e7-5b34-4de4-b131-e8c6d4547629.png)

**Comment by adamrher** [comment]
I see. Well I guess the big picture here is that we don't have to resolve this with the ghg_mam4 PR; we can always namelist in a new lbc file that we feel is more appropriate. 

Is it the case that the latitudinal dependent LBC CO2 is only for runs with dynamic CO2 tracer/chemistry? For runs where CO2 is not an advected species, using a latitudinal LBC might be a bit strange as it would just set the entire column to latitudinal dependent CO2 value --- as you said it's not realistic for the upper atmosphere to instantaneously "see" the surface value. And so a well mixed assumption, using a global mean value everywhere (with no seasonal cycle) might be more appropriate in those cases ... and so perhaps that's why there is no latitudinal dependence in F2000/FHIST.

**Comment by dan800** [comment]
"For runs where CO2 is not an advected species"  -- in an attempt to unify / simplify model configurations, I'd argue we don't create compsets that do this outside of the simpler model framework. As you point out, there are already a ton of chemistry pre-processor files that need to be maintained, so creating one with just one less tracer seems like a lot of headache for little reward. Anyone who really wants to do it can always make the necessary changes in the mod source directory and namelist.  Which compsets were you thinking you want to have a version that uses a single number fixed number? I'm struggling to see why you would want a single annual mean for any run unless you were running aquaplanet or had set the obliquity to zero and there were no seasons. Presumably any component that sees the CO2 at the surface would benefit from a more realistic representation of the CO2 variability (or if not benefit, not care if it varies). A perpetual fixed year run (e.g., F2000 or F2010) still experiences seasons and the fluctuations in CO2.

**Comment by adamrher** [comment]
I'm fine with what you're proposing --- don't create new compsets outside of simpler models that use a global mean/annual mean CO2 value. I don't think anyone should be arguing for the global mean approach due to the marginal cost of one more tracer. 

That leads to another question about the new compset naming convention work. We are not just renaming; we are switching to -chem ghg_mam4. I think we need to make this clear in the other thread https://github.com/ESCOMP/CAM/issues/765. Are we **replacing** all F-case compsets, or are we adding on top of them? I think this detail is important given the enormity of F-cases currently supported in cime_config/config_compsets.xml. If we are just adding on top of them, e.g., let F2000climo stick around, then they should be removed before the cesm3 release, to comply with your proposal.

**Comment by dan800** [comment]
Agree they should be removed before the release - we'll already be doubling the number of compsets with LT and MT equivalents. The _v0a, _v0b naming convention mentioned in the other thread is to indicate these are test /dev compsets - the _v* will go away on release as well.

**Comment by swrneale** [comment]
@dan800 just out of interest what would a plot of the global average concentrations we have historically used look like compared to your above curves?
