### ISSUE TITLE
Option to turn on HB where CLUBB is not active

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [ESCOMP/CAM#846]
### What is the feature/what would you like to discuss?

To address stability issues with non-FV dynamical cores we would like to turn on Holtslag-Boville PBL scheme where CLUBB is not active. This code change will help address

https://github.com/ESCOMP/CAM/issues/772

Science discussion here:

https://github.com/NCAR/amwg_dev/discussions/284

Have code ready and will start PR when time permits ... branch with code mods here:

https://github.com/PeterHjortLauritzen/CAM/tree/clubb_hb

### Is there anyone in particular you want to be part of this conversation?

@adamrher @JulioTBacmeister @fvitt 

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes

**Comment by tto061** [comment]
Hi Peter, here's my proposed version for vertical_diffusion.F90 where only the free-atmosphere diffusivity is calculated (and applied). I also highlight the tuning paramter of the (square) mixing length, ml2 (sticking to the original code, where it's unnecessarily a vector of constants set every time, but just for clarity). 

Note (from the declarations in vertical_diffusion_tend) that the subroutine turbintd should be made public in hb_diff.F90, or, as I think perhaps would be better, it could be moved as an additional public module in plb_utils (since it is generic and not tied to the Holtslag-Boville scheme).

Please note that I did not test this yet, for now it's just an idea.

[vertical_diffusion.F90.gz](https://github.com/ESCOMP/CAM/files/11851461/vertical_diffusion.F90.gz)
