### ISSUE TITLE
COSP output is incorrect

### ISSUE THREAD

**Issue by brianpm** [ESCOMP/CAM#880]
### What happened?

This is following up from recent difficulties in running COSP with development versions of CAM (reported to me from other users). Test simulations show that COSP output is incorrect. The various cloud fraction diagnostics show a mix of missing values and, when they aren't missing, they appear to be quantized to integer multiples of 10. 

Most testing was conducted with `cam6_3_123`: 
- global 5-day run with F2000climo at ne30pg3
- SCAM runs with arm95 case

The SCAM arm95 case seems to reproduce the issue. COSP output is mostly missing, and the cloud fractions appear to be always multiples of 10. The netCDF file says the variables are float but they appear like integer multiples of 10 (just using ncdump to look at the values).

_Just to be clear, there are expected missing values on time steps when COSP is not active, but there are also missing values on time steps when COSP is active. For example, with the SCAM cases COSP defaults to running every 3 hours, so there should be values every 9 time steps (dt=1200s). This is often the pattern of values, but various cloud fraction diagnostics like CLHMODIS and CLDTOT_ISCCP report longer runs of missing values. I also confirmed that there are times when those variables are missing when they should not be, e.g., `np.sum( np.isnan(case1['CLDTOT_ISCCP'].squeeze()) & (case1['SOLIN']>0) )` which for my case gave 174 times when there is sunshine but the cloud fractions are missing; that value is what appears for all the ISCCP and MODIS cloud fractions, but the MISR values are almost entirely missing._

## additional testing
I did a fresh git clone of CAM, checked out an older tag (`cam6_3_111`, chosen arbitrarily), and reproduced the issue. I then did a `git checkout cam6_3_088` to go back farther. To get `checkout_externals` to work, I had to delete clubb, silhs, and cice directories, but then it seemed to run ok. That tag (088) also produces the issue. 

As far as I can tell, nothing within COSP has changed, so I guess the problem must be on the CAM side. I haven't found anything in `cospsimulator_intr.F90` that has changed recently. I did notice that it has changed compared to the "released" version of CESM, so I tried transplanting the old version into `cam6_3_123`. I had to change the call to `qsat_water` to get that build. That produces the same issues as with the current `cospsimulator_intr.F90`. So my guess is that whatever is going on is due to a change in the input values that COSP gets.

A potential additional hint is that `PCTMODIS` is supposed to be the cloud top pressure in Pa, but in my SCAM output the values are of the order 10^5 instead of the expected 10^4. The corresponding ISCCP variable is `MEANPTOP_ISCCP` and it seems to be even more off from expected.

## request
I'm not sure whether I am going to be able to track down this error on my own. I would like some help. 

### What are the steps to reproduce the bug?

```
> git checkout cam6_3_123
> cd cime/scripts
> create_newcase --case $CASENAME --compset FSCAM --res T42_T42 --user-mods-dir ../../cime_config/usermods_dirs/scam_arm95 --walltime 00:10:00
> cd $CASENAME
> xmlchange --append CAM_CONFIG_OPTS="-cosp"
> case.setup
> case.build
> case.submit
```
Look at the COSP output in the resulting file. Examples:
- FISCCP1_COSP
- CLDTOT_ISCCP
- CLMODIS
- CLDHGH_CAL
- CLD_MISR

### What CAM tag were you using?

cam6_3_123

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/work/brianpm/my_cases/cam6p3p123.scam.ne30pg3.cosp02

### Will you be addressing this bug yourself?

No

**Comment by brianpm** [comment]
I did another run with the tag `cesm2.1-exp007` (just because I had it sitting in my directory). The Externals file suggest this is `cam6_0_026` but when I cd into the components/cam directory and do git status it says `cam_cesm2_1_rel_41`. 

In any case, it seems like this also is producing these discrete values of cloud fractions (10, 20, 30, ...). 

(case directory: `/glade/work/brianpm/my_cases/cesmRelease.scam.cosp01`)

**Comment by gold2718** [comment]
> I did another run with the tag `cesm2.1-exp007` (just because I had it sitting in my directory). The Externals file suggest this is `cam6_0_026` but when I cd into the components/cam directory and do git status it says `cam_cesm2_1_rel_41`.

I am confused by this. CAM in `cesm2.1-exp007` is an svn checkout, not a git repo. Are you sure your `checkout_externals` on `cesm2.1-exp007` succeded? I would guess to switch from a CESM tag using a git CAM external to one using svn (or the reverse), you would first have to remove components/cam.

**Comment by brianpm** [comment]
@gold2718 -- This was definitely downloaded with a git clone command, but I don't know when or what I've done with it since I first used it. I just had that in my work directory. I'll do a fresh git clone of CESM to confirm this result.

**Comment by gold2718** [comment]
> @gold2718 -- This was definitely downloaded with a git clone command, but I don't know when or what I've done with it since I first used it. I just had that in my work directory. I'll do a fresh git clone of CESM to confirm this result.

The CESM tag is git, however, the CAM external `cam6_0_026` is svn.

**Comment by brianpm** [comment]
I did a completely fresh git clone of CESM and checked out `release-cesm2.2.1` and repeated the SCAM case.

Seems like the problem is present. Cloud fractions are all either missing or multiples of 10: `CLD_CAL`, `CLD_MISR`, `CLMODIS`, `FISCCP1_COSP`. 

Case directory: /glade/work/brianpm/my_cases/cesmRelease.scam.cosp02

Example output: /glade/scratch/brianpm/archive/cesmRelease.scam.cosp02/atm/hist/cesmRelease.scam.cosp02.cam.h0.1995-07-18-19800.nc

**Comment by brian-eaton** [comment]
Hi @brianpm.  I have been looking into this issue and wanted to post what I've found so far.

First, note that COSP was broken with the `cam_dev` physics until tag `cam6_3_105` which resolved issue #776.

Regarding the observation that cloud fractions (in percent) seem to all be multiples of 10: it turns out that this is correct, but it will mainly be observed looking at instantaneous output.  The multiples of 10 are a consequence of running the COSP simulator with 10 subcolumns.  The cloud fraction is a count of the subcolumns in a CAM gridbox that contain cloud, so the fractions range from 0 - 10 divided by the total number of subcolumns.  The number of subcolumns is user settable  with the namelist variable `cosp_ncolumns` and it defaults to 10 when no particular simulator is specified.  If for example you set the number of subcolumns to 50 then the instantaneous output would be in multiples of 2.  The time averaging is what changes the values from the integer multiples.

Regarding the occurance of fill values where there are daylight columns: I'm only partly able to reproduce this result.  I started doing tests on an `FV 10x15` grid and found that there were no instances in the `CLDTOT_ISCCP` field where fill values occured and the column was in daylight.  I did a 5 day run of `F2000climo` and put 5 day average output in h0, and instantaneous output (3-hrly) in h1.  In all time samples of `CLDTOT_ISCCP`, both instantaneous and time averaged, the daylight columns corresponded to columns with valid values of `CLDTOT_ISCCP`.  Next I tried the same test, but using `SE, ne30pg3`.  In this case all the instantaneous output of `CLDTOT_ISCCP` had valid values wherever `SOLIN>0`.  But I did find 69 columns (out of 48600) of fill values in the 5-day average output at columns where `SOLIN>0` .  In all these occurances the value of `SOLIN` was less than 2.5 W/m2, which implies these columns are near the seasonal terminator.  Since this behavior doesn't occur in the instantaneous output I suspect it's related to the time averaging.

That's it for now.  I'll pursue this further.

**Comment by brianpm** [comment]
Thanks, @brian-eaton! I wondered if I was misinterpreting the multiples of 10, but couldn't think of why it would look like that. 

I wonder if some of the other strange values I was observing are also because of looking at instantaneous output in SCAM. 

Looking at my 5-day global run again, it doesn't look as bad as I thought. I think my numbers might have been off because in my daily average file, the entire first day looks like it is missing. After that first day, `CLDTOT_ISCCP` appears to have valid values outside of of the Arctic (polar night).  And `CLDTOT_CAL` has values at the pole, too, so is only missing on the first day. So I might have fooled myself by looking at the first time slice of the `h1` file. 

My SCAM runs do show values of `CLDTOT_ISCCP` that are missing when SOLIN is much larger than 0, as shown in this figure. The regular spacing of the missing `CLDTOT_ISCCP` values, however, makes me think this has to do with running COSP less frequently than radiation. I can test to confirm that is the case.  

![image](https://github.com/ESCOMP/CAM/assets/5471157/2d944fb8-10f5-4e76-8f7c-8340059ff665)

So it seems likely that COSP is working, and I should have been more careful in my testing. Sorry for the trouble!!

If we do think COSP is behaving correctly in these cases, I'd like to investigate what is happening in the 93-level version of the model ("FMT" compset with cam_dev physics). This is reported to be crashing (and is why I started these experiments).

**Comment by brianpm** [comment]
Thanks again, @brian-eaton!

With your testing, I'm feeling pretty confident that COSP is behaving as expected for regular CAM6. I pulled the trigger too fast on filing this issue, but I'm glad that we've taken a closer look. At this point, will close this issue. I'm going to follow up with testing the cam_dev physics and/or the L58 and L93 configurations (that latter is the one that is reported to be crashing).
