### ISSUE TITLE
error in using ESMF library in subroutine set_time_float_from_date

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CAM#92]
The following error occurs when using the NUOPC/CMEPS cap for the prealpha test 
`ERS_Ld3_Vnuopc.f09_f09_mg17.FCfireHIST.cheyenne_intel.cam-outfrq1d
`
```
ESMCI_Calendar.C:1161 ESMCI::Calendar::convertToTime() Input argument out of range  - ; NoLeap: for month 2, dd=29 > 28 days in the month.
 ESMCI_Time.C:333 ESMCI::Time::set() Input argument out of range  - Internal subroutine call returned Error
```

This error is triggered by the call to routine solar_irrad_init in module solar_data
   ```
call solar_irrad_init( solar_irrad_data_file, fixed_solar, solar_data_ymd, solar_data_tod, &
                           solar_const, solar_htng_spctrl_scl )
```
and in turn solar_irrad_init calls 
   ```
call time_coord%initialize( filepath, fixed=fixed, fixed_ymd=fixed_ymd, fixed_tod=fixed_tod, &
                                force_time_interp=.true., try_dates=.true. )
```
which calls

`call set_time_float_from_date( ref_time, ref_yr, ref_mon, ref_day, tod )
`

where the following code block extists:

```
call ESMF_TimeSet( date, yy=year, mm=month, dd=day, s=sec, calendar=tm_cal, rc=rc)
  !
  ! If the subroutine returned error, check if it is Feb 29 of a non-leap year
  ! (legitimately used by the time-interpolation routines in tracer_data.F90)
  ! in which case, substitute Feb 28 for the day
  !
  if ( rc .ne. ESMF_SUCCESS ) then
     if ( ( month .eq. 2 ) .and. ( day .eq. 29 ) ) then ! assume the failure is because it is leap day
        useday = 28
        call ESMF_TimeSet( date, yy=year, mm=month, dd=useday, s=sec, calendar=tm_cal, rc=rc)
     else  ! legitimate error, let the model quit
        call chkrc(rc, sub//': error return from ESMF_TimeSet for set_time_float_from_date')
     endif
  endif
```
The problem is that the following call 
**call ESMF_TimeSet( date, yy=year, mm=month, dd=day, s=sec, calendar=tm_cal, rc=rc)**
returns an error when the ESMF library is used.  

One solution to this is to have determine if the calendar is no_leap and if the month is 2 and the day is 29 - and if so call ESMF_TimeSet only once with Feb. 28 - otherwise just call ESMF_TimeSet.

**Comment by fvitt** [comment]
@mvertens 

What version of CIME is needed for NUOPC?
I get the following error with this test:

RUNNING TESTS:
  ERS_Ld3_Vnuopc.f09_f09_mg17.FCfireHIST.cheyenne_intel.cam-outfrq1d
Starting CREATE_NEWCASE for test ERS_Ld3_Vnuopc.f09_f09_mg17.FCfireHIST.cheyenne_intel.cam-outfrq1d with 1 procs
Finished CREATE_NEWCASE for test ERS_Ld3_Vnuopc.f09_f09_mg17.FCfireHIST.cheyenne_intel.cam-outfrq1d in 0.309858 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /glade/scratch/fvitt/ERS_Ld3_Vnuopc.f09_f09_mg17.FCfireHIST.cheyenne_intel.cam-outfrq1d.noleap_nuopc
    Errors were:
        ERROR: Makes no sense to have empty read-only file

Due to presence of batch system, create_test will exit before tests are complete.
To force create_test to wait for full completion, use --wait
At test-scheduler close, state is:
FAIL ERS_Ld3_Vnuopc.f09_f09_mg17.FCfireHIST.cheyenne_intel.cam-outfrq1d (phase CREATE_NEWCASE)
    Case dir: /glade/scratch/fvitt/ERS_Ld3_Vnuopc.f09_f09_mg17.FCfireHIST.cheyenne_intel.cam-outfrq1d.noleap_nuopc
test-scheduler took 0.411540985107 seconds

**Comment by mvertens** [comment]
@fvitt  - you need to update CIME, CMEPS, CAM and CLM to get this test working. I can provide the hashese - but it would be easier if you could make this change in the mct side and validate that its bfb - I can verify on the nuopc end while I am sorting through other tests failures as well. This is the first time I have run the cesm prealpha tests with nuopc.
