### ISSUE TITLE
PUMAS update for vapor deposition onto snow

### ISSUE THREAD

**Issue by Katetc** [ESCOMP/CAM#936]
### Issue Type

Externals Update

### Issue Description

@adamrher and @andrewgettelman want to add a single-line code update to PUMAS that fixes a problem with vapor deposition onto snow. This will be an answer-changing update for all composts that include PUMAS, so we will put it in its own CAM PR.

### Will this change answers?

Yes

### Will you be implementing this yourself?

Yes

**Comment by andrewgettelman** [comment]
Correction: this is NOT a conservation problem. It is an adjustment because @adamrher indicated he did not like the impact of vapor deposition onto snow.

There is not a conservation problem.  

This modification reduces vapor deposition onto snow in PUMAS in a way consistent with the original vapor deposition treatment.

**Comment by cacraigucar** [comment]
Will the upcoming PR which implements this need to be pushed through fairly quickly (ie will it be for Cecile's runs)?

**Comment by adamrher** [comment]
Yes, fairly quickly. Will plan to discuss the exact priority level tmrw.

**Comment by adamrher** [comment]
Adding results to this git thread because there are concerns about bringing in science changes this late in the game. Personally my opinion is that has a small impact on clouds (see below -0.63 W/m2), and is the right thing to do (it adds consistent by using the same limiter for snow that is used for rain).

[AMWG diags](https://webext.cgd.ucar.edu/F2000climo/cam6_3_097_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_1800pes_231128_mg2_limvapdeps_Nx2yrs/atm/cam6_3_097_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_1800pes_231128_mg2_limvapdeps_Nx2yrs.2_8-cam6_3_097_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_1800pes_231115_mg2_Nx2yrs.2_10/) w/ and w/o the new limiter.

![temp_SWCF](https://github.com/ESCOMP/CAM/assets/29961476/fcc3234c-6fa5-4300-9c42-a9c8789f6806)

**Comment by adamrher** [comment]
Now I remember @PeterHjortLauritzen and I discussed a plan to submit a new coupled run with those mod once we take a look at 66. I will take care of this and provide an update in this thread.
